### ISSUE TITLE
Unable to run the script

### ISSUE THREAD

**Issue by psubhashish** [alexram1313/text-to-speech-sample#1]
Tried to run the script on a Mac but failed to do so. Attached the screenshot. 
<img width="568" alt="screen shot 2017-05-29 at 2 17 12 pm" src="https://cloud.githubusercontent.com/assets/1258090/26542683/92bda938-4478-11e7-9bba-9eaddd2932d1.png">

**Comment by alexram1313** [comment]
What's it's pointing out is a type annotation that is valid syntax in Python 3. So make sure to run it in Python 3+

**Comment by psubhashish** [comment]
Well, I tried that too. (see below) BTW I have installed Homebrew.
<img width="528" alt="python3_error" src="https://cloud.githubusercontent.com/assets/1258090/26546985/5ff8d2d6-448a-11e7-984b-05b17427697b.png">

**Comment by alexram1313** [comment]
I mentioned in the video that this required PyAudio but unfortunately neglected to show the installation process. Sorry.

From terminal, use the following commands:
`brew install portaudio`
`pip install pyaudio`
using the pip corresponding to the python3 installation.

Source: <a href="https://people.csail.mit.edu/hubert/pyaudio/">https://people.csail.mit.edu/hubert/pyaudio/</a>

**Comment by psubhashish** [comment]
I actually realized about that when I was trying earlier. Pyaudio is already installed in my computer. 
<img width="555" alt="pyaudio already installed" src="https://cloud.githubusercontent.com/assets/1258090/26547880/cbc0808c-448e-11e7-93fd-225e0b4c72bb.png">

**Comment by alexram1313** [comment]
From the file path, it seems it was installed for Python 2.7 but not for 3. In the command, try replacing `pip` with `pip3` or whatever name corresponds to the correct installation.

**Comment by psubhashish** [comment]
It worked. Thank you so very much! 👍 🥇
