### ISSUE TITLE
Cannot run script

### ISSUE THREAD

**Issue by MrBreadWater** [alexram1313/text-to-speech-sample#3]
Whenever I run the script, I get this error: 
Traceback (most recent call last):
  File "E:\TTS\load.py", line 63, in <module>
    tts = TextToSpeech()
  File "E:\TTS\load.py", line 15, in __init__
    self._load_words(words_pron_dict)
  File "E:\TTS\load.py", line 21, in _load_words
    key, val = line.split('  ',2)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by alexram1313** [comment]
There should be 2 spaces in the first argument for line.split. Could you print the value of line?

**Comment by MrBreadWater** [comment]
Do you mean this one? 
`key, val = line.split('  ',2)`

**Comment by alexram1313** [comment]
Yeah, but before that, could you type `print(line)` and reply with the result?

**Comment by MrBreadWater** [comment]
Sorry, not quite sure what you were asking for. I'm a bit of a python noob. I put `print(line)` on the line before `key, val = line.split(' ',2)` but I got the same output when run.
EDIT: Woops, thats not true. There was a new line I didn't see. It wont copy and paste for some reason, but I will type it out manually. Here: `ÿþ; ; ;    #    C M U D I C T    - -     M a j o r   V e r s i o n :  0 . 0 7`

**Comment by alexram1313** [comment]
Looks like something messed up in the dictionary file. Try redownloading cmu-dict.

**Comment by MrBreadWater** [comment]
Ok I will try that. I copied and pasted it to a txt file rather than downloading.

**Comment by MrBreadWater** [comment]
Yeah that fixed it! Thanks
